spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootex
    username: bootuser
    password: bootuser

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true # 업로드 가능 여부
      location: C:\Users\gmlwh\Desktop\bootTest # 업로드된 파일 임시 저장 경로
      max-request-size: 30MB # 한 번 최대 업로드 가능 용량
      max-file-size: 10MB # 파일 하나의 최대 크기

org:
  zerock:
    upload:
      path: C:\Users\gmlwh\Desktop\bootTest